version: "3.3"
services:
  development:
    image: trufflesuite/ganache:v7.8.0
    ports:
      - 8545:8545
      - 8546:8546
    command: --chain.chainId 2018 -p 8545 -m "${TEST_MNEMONIC}"
  testchain0:
    build: ./besu/chain0
    ports:
      - 8645:8545
      - 8646:8546
  testchain1:
    build: ./besu/chain1
    ports:
      - 8745:8545
      - 8746:8546
