name: Test
on: [push, pull_request]
jobs:
  contract-test:
    name: Contract test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run tests
      run: forge test -vvv --use solc:0.8.9

  integration-test:
    name: Intergration test
    needs: contract-test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./pkg/...

    - name: Resolve dependencies
      run: npm install

    - name: apply the patch
      run: sed -i -e 's/20000,/200000,/' ./node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js

    - name: Setup ganache-cli
      run: NO_GEN_CODE=1 ./scripts/setup.sh development

    - name: Integration test
      run: make integration-test

    - name: Setup chains for E2E test
      run: NO_GEN_CODE=1 ./scripts/setup.sh testtwochainz

    - name: E2E test
      run: make e2e-test
