name: Test
on: [push, pull_request]

env:
  SOLC_VERSION: 0.8.9

jobs:
  contract-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Resolve dependencies
      run: npm install

    - name: Build and Check sizes
      run: forge build --sizes --skip test --use solc:${{ env.SOLC_VERSION }}

    - name: Run tests
      run: forge test -vvvv --gas-report --use solc:${{ env.SOLC_VERSION }}

    - name: Linting
      run: make lint

  integration-test:
    name: Integration test
    needs: contract-test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./pkg/...

    - name: Build Relayer
      run: make yrly

    - name: Resolve dependencies
      run: npm install

    - name: Setup ganache-cli
      run: NO_GEN_CODE=1 ./scripts/setup.sh development

    - name: Integration test
      run: make integration-test

    - name: Setup chains for E2E test
      run: NO_GEN_CODE=1 ./scripts/setup.sh testtwochainz

    - name: E2E test
      run: make e2e-test
